'use strict';

/* داده‌های نمونه پروژه‌ها: بعداً این‌ها را با پروژه‌های واقعی خودم جایگزین می‌کنم. */
const PROJECTS = [
  {id:'shop',title:'فروشگاه کوچک',type:'فول‌استک',tags:['Django','Python','JavaScript'],status:'نمونه اولیه',featured:true,desc:'یک فروشگاه ساده برای نمایش محصول، سبد خرید و مدیریت اطلاعات؛ مناسب برای تمرین ارتباط فرانت‌اند و بک‌اند.',problem:'می‌خواستم بفهمم یک فروشگاه از پشت صحنه چطور داده محصول و سبد خرید را مدیریت می‌کند.',solution:'ساختار پروژه را با Django برای داده‌ها و JavaScript برای تعاملات سمت کاربر طراحی کردم.',learned:'کار با مدل، URL، View، قالب‌ها و منطق ساده سبد خرید را بهتر فهمیدم.',challenge:'هماهنگ نگه داشتن وضعیت سبد خرید و طراحی تجربه مناسب در موبایل.',tech:['Python','Django','JavaScript','SQLite']},
  {id:'task',title:'مدیریت کارها',type:'فرانت‌اند',tags:['JavaScript','HTML','CSS'],status:'نمونه اولیه',desc:'یک ابزار ساده برای اضافه کردن، تکمیل، حذف و فیلتر کردن کارهای روزانه بدون نیاز به حساب کاربری.',problem:'می‌خواستم یک برنامه کوچک بسازم که سریع باشد و اطلاعاتش در مرورگر باقی بماند.',solution:'منطق برنامه را با JavaScript خالص و ذخیره‌سازی را با localStorage پیاده کردم.',learned:'مدیریت State، Event Delegation و ساخت UI از روی داده‌ها را تمرین کردم.',challenge:'حفظ تجربه کاربر هنگام فیلتر کردن و رندر دوباره لیست.',tech:['JavaScript','localStorage','CSS']},
  {id:'weather',title:'داشبورد آب‌وهوا',type:'فرانت‌اند',tags:['JavaScript','REST API'],status:'نمونه اولیه',desc:'جستجوی شهر و نمایش وضعیت آب‌وهوا با حالت‌های Loading، خطا و نتیجه خالی.',problem:'می‌خواستم اولین تجربه جدی خودم با یک API واقعی را داشته باشم.',solution:'با fetch داده را گرفتم و برای حالت‌های مختلف درخواست، UI جدا طراحی کردم.',learned:'کار با API، JSON، async/await و مدیریت خطا را بهتر یاد گرفتم.',challenge:'نمایش خطاهای قابل فهم و جلوگیری از پرش Layout هنگام Loading.',tech:['JavaScript','REST API','CSS']},
  {id:'api',title:'Blog API',type:'بک‌اند',tags:['Python','Django','REST API'],status:'نمونه اولیه',desc:'یک API ساده برای نوشته‌های وبلاگ با عملیات ایجاد، خواندن، ویرایش و حذف.',problem:'می‌خواستم API را از سمت ساختن، نه فقط مصرف کردن، یاد بگیرم.',solution:'Endpointهای اصلی را با Django طراحی و پاسخ‌ها را به شکل JSON آماده کردم.',learned:'مفهوم HTTP، Status Code، اعتبارسنجی و ساختار API برایم روشن‌تر شد.',challenge:'جدا کردن منطق پروژه و برگرداندن خطاهای درست به کلاینت.',tech:['Python','Django','REST API']},
  {id:'portfolio',title:'همین پورتفولیو',type:'فرانت‌اند',tags:['HTML','CSS','JavaScript'],status:'در حال توسعه',desc:'یک پورتفولیوی فارسی و RTL که UX ساده را با انیمیشن‌های مدرن و جستجوی واقعی ترکیب می‌کند.',problem:'به یک سایت نیاز داشتم که هم مهارت‌هایم را نشان دهد و هم خودش نمونه‌کار شماره یک من باشد.',solution:'بدون فریم‌ورک، یک سیستم داده‌محور برای پروژه‌ها، فیلتر، جستجو، مودال و انیمیشن ساختم.',learned:'فهمیدم طراحی تجربه کاربر فقط ظاهر نیست و جزئیات کوچک روی حس محصول اثر زیادی دارند.',challenge:'زیبا کردن Animationها بدون سنگین یا گیج‌کننده کردن تجربه.',tech:['HTML','CSS','JavaScript','Responsive Design']},
  {id:'expense',title:'مدیریت هزینه‌ها',type:'بک‌اند',tags:['Python','SQLite'],status:'نمونه اولیه',desc:'یک ابزار ساده برای ثبت هزینه‌ها، دسته‌بندی آن‌ها و دیدن خلاصه ماهانه در محیط خط فرمان.',problem:'می‌خواستم ساختار یک برنامه چندبخشی و کار با دیتابیس را در Python تمرین کنم.',solution:'داده‌ها را در SQLite نگه داشتم و بخش‌های ثبت، نمایش و خلاصه‌سازی را جدا کردم.',learned:'تفکیک داده، منطق و نمایش و کوئری‌های ساده SQL را تمرین کردم.',challenge:'اعتبارسنجی ورودی و مدیریت تاریخ بدون خراب شدن برنامه.',tech:['Python','SQLite','SQL']}
];
const FILTERS=['همه','فرانت‌اند','بک‌اند','فول‌استک','JavaScript','Python','Django'];
const SKILLS=[
  ['HTML','فرانت‌اند','راحت','99%','ساختار معنایی و دسترس‌پذیر'],['CSS','فرانت‌اند','راحت','98%','Responsive، Grid، Flex و انیمیشن'],['JavaScript','فرانت‌اند','در حال تمرین','75%','DOM، Eventها، API و منطق رابط'],['Python','بک‌اند','راحت','30%','منطق برنامه، توابع، OOP و ساختار کد'],['Django','بک‌اند','در حال تمرین','20%','مسیر فعلی یادگیری من برای وب و بک‌اند'],['Git','ابزار','در حال تمرین','20%','مدیریت نسخه و نگهداری پروژه‌ها']
];
const BUILD=[['◫','وب‌سایت ریسپانسیو','سایت‌هایی که روی موبایل و دسکتاپ درست و راحت کار کنند.'],['✦','لندینگ‌پیج','صفحه‌های معرفی مدرن برای محصول، برند یا کسب‌وکار.'],['⌘','وب‌اپلیکیشن','ابزارهای کاربردی کوچک مثل مدیریت کار، داشبورد و فرم‌های تعاملی.'],['⌁','REST API','ساخت APIهای ساده برای ارتباط بین رابط کاربری و بک‌اند.'],['▣','بک‌اند با Django','مدیریت داده، مسیرها، منطق برنامه و بخش‌های سمت سرور.'],['↗','رابط تعاملی','رابط‌هایی که فقط زیبا نیستند و رفتارشان به کاربر بازخورد می‌دهد.']];
const SECTIONS=[['خانه','معرفی و خلاصه','home'],['درباره من','مسیر یادگیری و رویکرد کاری','about'],['مهارت‌ها','تکنولوژی‌هایی که امروز با آن‌ها کار می‌کنم','skills'],['پروژه‌ها','نمونه‌کارها و جزئیات پروژه‌ها','projects'],['چه می‌سازم؟','خدمات و کارهایی که می‌توانم شروع کنم','build'],['تماس','راه‌های ارتباطی','contact']];
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const reduced=()=>window.matchMedia('(prefers-reduced-motion: reduce)').matches;
const esc=s=>String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));

function preview(){return `<div class="preview"><div class="preview__bar"><i></i><i></i><i></i></div><div class="preview__body"><span class="preview__line"></span><span class="preview__line"></span><span class="preview__line"></span><span class="preview__line"></span></div></div>`}
function chips(items){return items.map(x=>`<span class="chip">${esc(x)}</span>`).join('')}
function card(p,i){return `<article class="project-card reveal" data-id="${p.id}" style="--delay:${Math.min(i,7)*45}ms"><div class="project-card__media">${preview()}<span class="project-type">${esc(p.type)}</span></div><div class="project-card__body"><h3>${esc(p.title)}</h3><p>${esc(p.desc)}</p><span class="project-meta">${esc(p.status)} · ${p.tags.length} تکنولوژی</span><div class="chips">${chips(p.tags)}</div><div class="project-card__actions"><button class="btn btn--primary" data-open="${p.id}">جزئیات پروژه</button><a class="btn btn--ghost" href="https://github.com/your-username/${p.id}" target="_blank" rel="noopener">GitHub ↗</a></div></div></article>`}
function featured(p){return `<div class="featured__media">${preview()}</div><div class="featured__content"><span class="featured__badge">✦ پروژه شاخص</span><h3>${esc(p.title)}</h3><p>${esc(p.desc)}</p><div class="chips">${chips(p.tech)}</div><p><strong>چالش اصلی:</strong> ${esc(p.challenge)}</p><div class="featured__actions"><button class="btn btn--primary" data-open="${p.id}">داستان کامل پروژه ←</button><a class="btn btn--ghost" href="https://github.com/your-username/${p.id}" target="_blank" rel="noopener">GitHub</a></div></div>`}
function matches(p,q,f){const text=[p.title,p.type,p.desc,p.problem,p.solution,p.learned,p.challenge,...p.tags].join(' ').toLowerCase();const filter=f==='همه'||(f==='فرانت‌اند'&&p.type==='فرانت‌اند')||(f==='بک‌اند'&&p.type==='بک‌اند')||(f==='فول‌استک'&&p.type==='فول‌استک')||p.tags.includes(f);return filter&&(!q||text.includes(q.toLowerCase()))}
let state={q:'',f:'همه'};
function renderFilters(){const el=$('#filters');el.innerHTML=FILTERS.map(f=>{const count=PROJECTS.filter(p=>matches(p,'',f)).length;return `<button class="filter ${f===state.f?'is-active':''}" data-filter="${esc(f)}">${esc(f)} <b>${count}</b></button>`}).join('')}
function renderProjects(){const paint=()=>{const visible=PROJECTS.filter(p=>matches(p,state.q,state.f));const featuredProject=visible.find(p=>p.featured);$('#featuredProject').innerHTML=featuredProject?featured(featuredProject):'';$('#featuredProject').hidden=!featuredProject;const grid=visible.filter(p=>!featuredProject||p.id!==featuredProject.id);$('#projectsGrid').innerHTML=grid.map(card).join('');$('#emptyState').hidden=visible.length>0;$('#resultsMeta').textContent=`نمایش ${visible.length} از ${PROJECTS.length} پروژه · فیلتر: ${state.f}${state.q?` · جستجو: «${state.q}»`:''}`;observeReveals();attachSpotlight()};if(!reduced()&&document.startViewTransition){document.startViewTransition(paint)}else paint()}
function openProject(id){const p=PROJECTS.find(x=>x.id===id);if(!p)return;$('#modalContent').innerHTML=`<div class="modal__hero">${preview()}</div><div class="modal__body"><span class="featured__badge">${esc(p.type)} · ${esc(p.status)}</span><h2 id="modalTitle">${esc(p.title)}</h2><p>${esc(p.desc)}</p><div class="chips">${chips(p.tech)}</div><div class="detail-grid"><div class="detail-block"><h4>این پروژه چیست؟</h4><p>${esc(p.desc)}</p></div><div class="detail-block"><h4>چه مشکلی را حل می‌کند؟</h4><p>${esc(p.problem)}</p></div><div class="detail-block"><h4>من چه کاری انجام دادم؟</h4><p>${esc(p.solution)}</p></div><div class="detail-block"><h4>چه چیزی یاد گرفتم؟</h4><p>${esc(p.learned)}</p></div><div class="detail-block"><h4>چالش پروژه</h4><p>${esc(p.challenge)}</p></div><div class="detail-block"><h4>تکنولوژی‌ها</h4><p>${esc(p.tech.join(' · '))}</p></div></div><div class="featured__actions"><a class="btn btn--primary" href="https://github.com/your-username/${p.id}" target="_blank" rel="noopener">مشاهده در GitHub ↗</a></div></div>`;$('#projectModal').hidden=false;document.body.classList.add('is-locked')}
function closeProject(){ $('#projectModal').hidden=true;if($('#searchModal').hidden)document.body.classList.remove('is-locked') }
function initSkills(){ $('#skillsGrid').innerHTML=SKILLS.map(s=>`<article class="skill-card reveal"><div class="skill-card__top"><h3>${s[0]}</h3><span class="level">${s[2]}</span></div><p>${s[4]}</p><div class="skill-bar"><span style="--level:${s[3]}"></span></div></article>`).join('');observeReveals();attachSpotlight() }
function initBuild(){ $('#buildGrid').innerHTML=BUILD.map(x=>`<article class="build-card reveal"><div class="build-card__icon">${x[0]}</div><h3>${x[1]}</h3><p>${x[2]}</p></article>`).join('');observeReveals() }
function initHero(){const code=`const developer = {\n  name: "Matin",\n  role: "Junior Developer",\n  stack: ["HTML","CSS","JS","REACT","Python","Django"],\n  mindset: "learn → build → improve"\n};`;const el=$('#heroCode');if(reduced()){el.textContent=code}else{let i=0;const type=()=>{el.textContent=code.slice(0,i++);if(i<=code.length)setTimeout(type,12)};setTimeout(type,350)};const target=PROJECTS.length;let n=0;const count=()=>{n=Math.min(target,n+1);$('#projectCount').textContent=n;if(n<target&&!reduced())setTimeout(count,80)};setTimeout(count,300)}
function observeReveals(){const items=$$('.reveal:not(.is-visible)');if(reduced()||!('IntersectionObserver'in window)){items.forEach(x=>x.classList.add('is-visible'));return}const ob=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('is-visible');ob.unobserve(e.target)}}),{threshold:.08});items.forEach(x=>ob.observe(x))}
function attachSpotlight(){$$('.skill-card,.project-card').forEach(el=>{el.onpointermove=e=>{const r=el.getBoundingClientRect();el.style.setProperty('--mx',`${e.clientX-r.left}px`);el.style.setProperty('--my',`${e.clientY-r.top}px`);el.style.transform=`translateY(-8px) rotateX(${((e.clientY-r.top)/r.height-.5)*-2}deg) rotateY(${((e.clientX-r.left)/r.width-.5)*2}deg)`};el.onpointerleave=()=>{el.style.transform=''}})}
function initProjects(){$('#projectSearch').addEventListener('input',e=>{state.q=e.target.value.trim();renderProjects()});$('#clearSearch').addEventListener('click',()=>{$('#projectSearch').value='';state.q='';renderProjects();$('#projectSearch').focus()});$('#filters').addEventListener('click',e=>{const b=e.target.closest('[data-filter]');if(!b)return;state.f=b.dataset.filter;renderFilters();renderProjects()});$('#resetProjects').addEventListener('click',()=>{state={q:'',f:'همه'};$('#projectSearch').value='';renderFilters();renderProjects()});document.addEventListener('click',e=>{const b=e.target.closest('[data-open]');if(b)openProject(b.dataset.open)})}
function initGlobalSearch(){const modal=$('#searchModal'),input=$('#globalSearch'),list=$('#searchResults');let active=0;function results(q){const t=q.toLowerCase();const arr=[];SECTIONS.forEach(x=>{if(!t||x.join(' ').toLowerCase().includes(t))arr.push({title:x[0],meta:x[1],kind:'بخش',run:()=>location.hash=x[2]})});PROJECTS.forEach(p=>{if(!t||[p.title,p.desc,...p.tags].join(' ').toLowerCase().includes(t))arr.push({title:p.title,meta:p.type+' · '+p.tags.join(' · '),kind:'پروژه',run:()=>openProject(p.id)})});SKILLS.forEach(s=>{if(!t||s.join(' ').toLowerCase().includes(t))arr.push({title:s[0],meta:s[1]+' · '+s[2],kind:'مهارت',run:()=>location.hash='skills'})});return arr.slice(0,10)}function draw(){const r=results(input.value.trim());active=Math.min(active,r.length?active:0);list.innerHTML=r.length?r.map((x,i)=>`<li class="search-result ${i===active?'is-active':''}" data-index="${i}"><span class="search-result__icon">⌕</span><span><span class="search-result__title">${esc(x.title)}</span><span class="search-result__meta">${esc(x.meta)}</span></span><span class="search-result__kind">${esc(x.kind)}</span></li>`).join(''):`<li class="search-result"><span>چیزی پیدا نشد.</span></li>`;list._results=r;$('#searchHint').textContent=r.length?`${r.length} نتیجه · با ↑ ↓ و Enter انتخاب کن.`:'نتیجه‌ای پیدا نشد.'}function open(){modal.hidden=false;document.body.classList.add('is-locked');input.value='';active=0;draw();input.focus()}function close(){modal.hidden=true;if($('#projectModal').hidden)document.body.classList.remove('is-locked')}$('#searchTrigger').onclick=open;$('#globalClose').onclick=close;modal.addEventListener('click',e=>{if(e.target.closest('[data-search-close]'))close();const item=e.target.closest('[data-index]');if(item){const r=list._results[Number(item.dataset.index)];close();r?.run()}});input.addEventListener('input',draw);input.addEventListener('keydown',e=>{if(e.key==='Escape'){close();return}if(e.key==='ArrowDown'){e.preventDefault();active=(active+1)%(list._results?.length||1);draw();return}if(e.key==='ArrowUp'){e.preventDefault();active=(active-1+(list._results?.length||1))%(list._results?.length||1);draw();return}if(e.key==='Enter'){const r=list._results?.[active];close();r?.run()}});document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();open()}})}
function initContact(){const form=$('#contactForm');const fields=[['name','#nameError',v=>v.trim().length>=2],['email','#emailError',v=>/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(v.trim())],['message','#messageError',v=>v.trim().length>=10]];fields.forEach(([id,err,fn])=>{const el=$('#'+id);el.addEventListener('blur',()=>{el.classList.toggle('field-invalid',!fn(el.value))});el.addEventListener('input',()=>{if(el.classList.contains('field-invalid'))el.classList.toggle('field-invalid',!fn(el.value))})});form.addEventListener('submit',e=>{e.preventDefault();let ok=true;fields.forEach(([id,,fn])=>{const el=$('#'+id),valid=fn(el.value);el.classList.toggle('field-invalid',!valid);ok=ok&&valid});$('#formStatus').textContent=ok?'فرم از نظر ورودی کامل است. برای ارسال واقعی، ایمیل خودت را در تنظیمات سایت قرار بده.':''})}
function initNav(){const menu=$('#menuBtn'),nav=$('#nav');menu.onclick=()=>{const open=nav.classList.toggle('is-open');menu.setAttribute('aria-expanded',open)};$$('.nav__link').forEach(a=>a.onclick=()=>{nav.classList.remove('is-open');menu.setAttribute('aria-expanded','false')});const sections=SECTIONS.map(x=>[x[2],document.getElementById(x[2])]);const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){$$('.nav__link').forEach(a=>a.classList.toggle('is-active',a.getAttribute('href')==='#'+e.target.id))}}),{rootMargin:'-35% 0px -55%'});sections.forEach(x=>x[1]&&io.observe(x[1]))}
function initScroll(){const header=$('#header'),bar=$('#scrollProgress'),top=$('#toTop');const update=()=>{const y=scrollY,max=document.documentElement.scrollHeight-innerHeight;bar.style.width=`${max?y/max*100:0}%`;header.classList.toggle('scrolled',y>20);top.classList.toggle('is-visible',y>600)};addEventListener('scroll',update,{passive:true});top.onclick=()=>scrollTo({top:0,behavior:reduced()?'auto':'smooth'});update()}
function initParticles(){const host=$('.fx-particles');if(!host||reduced())return;const count=innerWidth<760?22:42;for(let i=0;i<count;i++){const p=document.createElement('i');p.className='fx-particle';p.style.left=`${Math.random()*100}%`;p.style.top=`${Math.random()*100}%`;p.style.setProperty('--duration',`${5+Math.random()*9}s`);p.style.setProperty('--delay',`${-Math.random()*9}s`);p.style.setProperty('--drift-x',`${-30+Math.random()*60}px`);p.style.setProperty('--drift-y',`${-45+Math.random()*90}px`);host.appendChild(p)}}
function initCursor(){const glow=$('#cursorGlow'),ring=$('.cursor-ring'),dot=$('.cursor-dot');if(reduced()||matchMedia('(pointer:coarse)').matches)return;document.body.classList.add('cursor-ready');let tx=innerWidth/2,ty=innerHeight/2,rx=tx,ry=ty;addEventListener('pointermove',e=>{tx=e.clientX;ty=e.clientY;glow.style.opacity='1';glow.style.left=tx+'px';glow.style.top=ty+'px';dot.style.left=tx+'px';dot.style.top=ty+'px'});const loop=()=>{rx+=(tx-rx)*.16;ry+=(ty-ry)*.16;ring.style.left=rx+'px';ring.style.top=ry+'px';requestAnimationFrame(loop)};loop();const hover='a,button,input,textarea,.skill-card,.project-card,.build-card,.search-trigger';document.addEventListener('pointerover',e=>{if(e.target.closest(hover))document.body.classList.add('cursor-hover')});document.addEventListener('pointerout',e=>{if(!e.relatedTarget||!e.relatedTarget.closest?.(hover))document.body.classList.remove('cursor-hover')});addEventListener('pointerdown',()=>{document.body.classList.add('cursor-click');setTimeout(()=>document.body.classList.remove('cursor-click'),120)})}
function init(){initHero();initSkills();initBuild();renderFilters();renderProjects();initProjects();initGlobalSearch();initContact();initNav();initScroll();initParticles();initCursor();observeReveals();$$('.magnetic').forEach(b=>{b.onpointermove=e=>{const r=b.getBoundingClientRect();b.style.transform=`translate(${(e.clientX-r.left-r.width/2)*.12}px,${(e.clientY-r.top-r.height/2)*.12}px)`};b.onpointerleave=()=>b.style.transform=''})
$('#modalClose').onclick=closeProject;$('#projectModal').addEventListener('click',e=>{if(e.target.closest('[data-close]'))closeProject()});document.addEventListener('keydown',e=>{if(e.key==='Escape'){closeProject();$('#searchModal').hidden=true;document.body.classList.remove('is-locked')}})}
addEventListener('DOMContentLoaded',init);
